version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: shadow_usdhkd_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shadow_usdhkd
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: